name: QA

on:
  push:
    branches: [ "develop" ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Prettier Action
  # You may pin to the exact commit or the version.
  # uses: creyD/prettier_action@31355f8eef017f8aeba2e0bc09d8502b13dbbad1
      uses: creyD/prettier_action@v4.3
      with:
          prettier_options: --write **/*.{js,md}
